// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as downloads$0 from "../../../../cry5tallize/xhs_spider_desktop/internal/modules/downloads/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "downloads:changed": downloads$0.EventBatch;
        }
    }
}
