// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as xhsapi$0 from "../../xhsapi/models.js";

export interface ActiveSnapshot {
    "run_id": string;
    "sequence": number;
    "tasks": Task[] | null;
}

export interface Batch {
    "id": string;
    "task_ids": string[] | null;
    "created_at_ms": number;
}

export interface BatchPlanInput {
    "snapshot_ids": string[] | null;
    "config": Config;
}

export interface Candidate {
    "id": string;
    "kind": MediaKind;
    "representation": Representation;
    "urls": string[] | null;
    "expected_bytes": number | null;
    "live_photo": boolean;
    "scenes": string[] | null;
    "video"?: xhsapi$0.VideoStream | null;
    "image"?: xhsapi$0.ImageVariant | null;
}

export interface CandidateCatalog {
    "note_type": string;
    "snapshot_id": string;
    "candidates": Candidate[] | null;
    "codec_groups": string[] | null;
    "scenes": string[] | null;
    "formats": string[] | null;
}

export interface Changes {
    "run_id": string;
    "sequence": number;
    "needs_resync": boolean;
    "batches": EventBatch[] | null;
}

export interface ChangesInput {
    "run_id": string;
    "sequence": number;
}

export interface Config {
    "schema_version": number;
    "media": MediaConfig;
    "output": OutputConfig;
    "dedup": DedupConfig;
    "execution": ExecutionConfig;
    "selection": Selection;
    "naming": Naming;
}

export interface CreateBatch {
    "request_id": string;
    "snapshot_ids": string[] | null;
    "config": Config;
}

export interface CreateTask {
    "request_id": string;
    "snapshot_id": string;
    "config": Config;
}

export interface DedupConfig {
    "mode": DedupMode;
    "force": boolean;
    "strict_hash": boolean;
}

export enum DedupMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    DedupOff = 0,
    SameOutput = 1,
};

export enum ErrorKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ErrorUnknown = 0,
    ErrorNetwork = 1,
    ErrorContent = 2,
    ErrorFileSystem = 3,
    ErrorStorage = 4,
};

export interface EventBatch {
    "schema_version": number;
    "run_id": string;
    "sequence": number;
    "emitted_at_ms": number;
    "needs_resync": boolean;
    "changes": Task[] | null;
}

export interface ExecutionConfig {
    "continue_on_error": boolean;
    "retries_per_url": number;
    "max_attempts": number;
}

export enum ExistingPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ExistingUnknown = 0,
    Overwrite = 1,
    SkipExisting = 2,
};

export interface Failure {
    "kind": ErrorKind;
    "message": string;
    "http_status": number;
    "retryable": boolean;
}

export enum HDRMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    HDRAny = 0,
    HDROnly = 1,
    HDRExclude = 2,
};

export enum IdentityConfidence {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    IdentityUnknown = 0,
    IdentityWeak = 1,
    IdentityStrong = 2,
};

export enum ImageMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ImageDefault = 0,
    ImageBest = 1,
    ImageAll = 2,
    ImageScenes = 3,
    ImageCustom = 4,
};

export interface ImageSelection {
    "mode": ImageMode;
    "candidate_ids": string[] | null;
    "scenes": string[] | null;
    "formats": string[] | null;
    "first_index": number;
    "last_index": number;
}

export interface Item {
    "id": string;
    "task_id": string;
    "sequence": number;
    "kind": MediaKind;
    "asset_key": string;
    "confidence": IdentityConfidence;
    "representation": Representation;
    "relative_path": string;
    "urls": string[] | null;
    "expected_bytes": number | null;
    "candidate_id"?: string;
    "state": ItemState;
    "transferred_bytes": number;
    "current_bytes": number;
    "current_total": number | null;
    "result": Result;
    "failure": Failure | null;
    "attempts": number;
}

export enum ItemState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ItemUnknown = 0,
    ItemPending = 1,
    ItemRunning = 2,
    ItemPaused = 3,
    ItemWaitingRetry = 4,
    ItemSucceeded = 5,
    ItemSkipped = 6,
    ItemFailed = 7,
    ItemCanceled = 8,
    ItemFinalizing = 9,
    ItemInterrupted = 10,
};

export interface ListInput {
    "limit": number;
    "before_at_ms": number;
    "before_id": string;
    "state": State;
    "note_id": string;
    "author_id": string;
}

export enum LiveMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    LiveDefault = 0,
    LiveBoth = 1,
    LiveStatic = 2,
    LiveMotion = 3,
    LiveExclude = 4,
};

export interface LivePair {
    "image_index": number;
    "static_keys": string[] | null;
    "motion_keys": string[] | null;
}

export interface MediaConfig {
    "video": boolean;
    "images": boolean;
    "video_cover": boolean;
    "live_photo_motion": boolean;
    "live_photo_static"?: boolean | null;
    "pretty": boolean;
    "text": boolean;
    "raw": boolean;
    "manifest": boolean;
}

export enum MediaKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    MediaUnknown = 0,
    MediaVideo = 1,
    MediaImage = 2,
    MediaMotion = 3,
    MediaPretty = 4,
    MediaText = 5,
    MediaRaw = 6,
    MediaManifest = 7,
};

export interface Naming {
    "directory_template": string;
    "file_template": string;
}

export interface OutputConfig {
    "directory": string;
    "existing_policy": ExistingPolicy;
}

export interface Page {
    "items": Task[] | null;
    "has_more": boolean;
    "next_at_ms": number;
    "next_id": string;
}

export interface Plan {
    "note_id": string;
    "snapshot_id": string;
    "title": string;
    "author_id": string;
    "author_name": string;
    "account_id": string;
    "config": Config;
    "relative_directory": string;
    "items": PlannedItem[] | null;
    "warnings": string[] | null;
    "hash": string;
    "live_pairs": LivePair[] | null;
}

export interface PlanInput {
    "snapshot_id": string;
    "config": Config;
}

export interface PlanPreview {
    "snapshot_id": string;
    "note_id": string;
    "title": string;
    "directory": string;
    "files": PreviewFile[] | null;
    "known_bytes": number;
    "unknown_sizes": number;
    "warnings": string[] | null;
}

export interface PlannedItem {
    "sequence": number;
    "kind": MediaKind;
    "asset_key": string;
    "confidence": IdentityConfidence;
    "representation": Representation;
    "relative_path": string;
    "urls": string[] | null;
    "expected_bytes": number | null;
    "candidate_id"?: string;
}

export interface Preset {
    "id": string;
    "name": string;
    "config": Config;
    "updated_at_ms": number;
}

/**
 * PreviewFile contains no signed URLs or inline file bodies.
 */
export interface PreviewFile {
    "sequence": number;
    "kind": MediaKind;
    "representation": Representation;
    "bytes": number | null;
    "relative_path": string;
}

export interface Representation {
    "codec_group"?: string;
    "codec"?: string;
    "format"?: string;
    "scene"?: string;
    "width"?: number | null;
    "height"?: number | null;
    "fps"?: number | null;
    "image_index"?: number | null;
    "bitrate"?: number | null;
    "stream_type"?: number | null;
    "hdr_type"?: number | null;
    "quality"?: string;
    "media_id"?: string;
}

export interface Result {
    "root": string;
    "relative_path": string;
    "bytes": number;
    "sha256": string;
    "mtime_ms": number;
    "skip_reason": SkipReason;
    "reused_item_id": string;
}

export interface SavePreset {
    "id": string;
    "name": string;
    "config": Config;
}

export interface Selection {
    "video": VideoSelection;
    "motion"?: VideoSelection | null;
    "images": ImageSelection;
    "live_photo": LiveMode;
}

export enum SkipReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    SkipNone = 0,
    SkipHistory = 1,
    SkipFileExists = 2,
};

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Unknown = 0,
    Queued = 1,
    Resolving = 2,
    Running = 3,
    Paused = 4,
    WaitingRetry = 5,
    Succeeded = 6,
    Partial = 7,
    Failed = 8,
    Canceled = 9,
    Interrupted = 10,
};

export interface Task {
    "id": string;
    "batch_id": string;
    "live_pairs": LivePair[] | null;
    "note_id": string;
    "snapshot_id": string;
    "title": string;
    "author_id": string;
    "author_name": string;
    "account_id": string;
    "state": State;
    "config": Config;
    "relative_directory": string;
    "plan_hash": string;
    "planned_items": number;
    "successful_items": number;
    "skipped_items": number;
    "failed_items": number;
    "fulfilled_items": number;
    "completed_bytes": number;
    "transferred_bytes": number;
    "current_item_id": string;
    "current_sequence": number;
    "current_bytes": number;
    "current_total": number | null;
    "failure": Failure | null;
    "created_at_ms": number;
    "started_at_ms": number | null;
    "finished_at_ms": number | null;
    "updated_at_ms": number;
    "revision": number;
}

export enum VideoMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    VideoDefault = 0,
    VideoBest = 1,
    VideoPerCodec = 2,
    VideoAll = 3,
    VideoCustom = 4,
};

export interface VideoSelection {
    "mode": VideoMode;
    "candidate_ids": string[] | null;
    "codec_groups": string[] | null;
    "containers": string[] | null;
    "min_long_edge": number;
    "max_long_edge": number;
    "max_short_edge": number;
    "width": number;
    "height": number;
    "min_fps": number;
    "max_fps": number;
    "hdr": HDRMode;
    "allow_unknown": boolean;
}
