// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActiveSnapshot {
    "run_id": string;
    "sequence": number;
    "tasks": Task[] | null;
}

export interface Changes {
    "run_id": string;
    "sequence": number;
    "needs_resync": boolean;
    "batches": EventBatch[] | null;
}

export interface ChangesInput {
    "run_id": string;
    "sequence": number;
}

export interface Config {
    "schema_version": number;
    "media": MediaConfig;
    "output": OutputConfig;
    "dedup": DedupConfig;
    "execution": ExecutionConfig;
}

export interface CreateTask {
    "request_id": string;
    "snapshot_id": string;
    "config": Config;
}

export interface DedupConfig {
    "mode": DedupMode;
    "force": boolean;
    "strict_hash": boolean;
}

export enum DedupMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    DedupOff = 0,
    SameOutput = 1,
};

export enum ErrorKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ErrorUnknown = 0,
    ErrorNetwork = 1,
    ErrorContent = 2,
    ErrorFileSystem = 3,
    ErrorStorage = 4,
};

export interface EventBatch {
    "schema_version": number;
    "run_id": string;
    "sequence": number;
    "emitted_at_ms": number;
    "needs_resync": boolean;
    "changes": Task[] | null;
}

export interface ExecutionConfig {
    "continue_on_error": boolean;
    "retries_per_url": number;
    "max_attempts": number;
}

export enum ExistingPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ExistingUnknown = 0,
    Overwrite = 1,
    SkipExisting = 2,
};

export interface Failure {
    "kind": ErrorKind;
    "message": string;
    "http_status": number;
    "retryable": boolean;
}

export enum IdentityConfidence {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    IdentityUnknown = 0,
    IdentityWeak = 1,
    IdentityStrong = 2,
};

export interface Item {
    "id": string;
    "task_id": string;
    "sequence": number;
    "kind": MediaKind;
    "asset_key": string;
    "confidence": IdentityConfidence;
    "representation": Representation;
    "relative_path": string;
    "urls": string[] | null;
    "expected_bytes": number | null;
    "state": ItemState;
    "transferred_bytes": number;
    "current_bytes": number;
    "current_total": number | null;
    "result": Result;
    "failure": Failure | null;
    "attempts": number;
}

export enum ItemState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ItemUnknown = 0,
    ItemPending = 1,
    ItemRunning = 2,
    ItemPaused = 3,
    ItemWaitingRetry = 4,
    ItemSucceeded = 5,
    ItemSkipped = 6,
    ItemFailed = 7,
    ItemCanceled = 8,
    ItemFinalizing = 9,
    ItemInterrupted = 10,
};

export interface ListInput {
    "limit": number;
    "before_at_ms": number;
    "before_id": string;
    "state": State;
    "note_id": string;
    "author_id": string;
}

export interface MediaConfig {
    "video": boolean;
    "images": boolean;
    "video_cover": boolean;
    "live_photo_motion": boolean;
    "pretty": boolean;
    "text": boolean;
    "raw": boolean;
    "manifest": boolean;
}

export enum MediaKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    MediaUnknown = 0,
    MediaVideo = 1,
    MediaImage = 2,
    MediaMotion = 3,
    MediaPretty = 4,
    MediaText = 5,
    MediaRaw = 6,
    MediaManifest = 7,
};

export interface OutputConfig {
    "directory": string;
    "existing_policy": ExistingPolicy;
}

export interface Page {
    "items": Task[] | null;
    "has_more": boolean;
    "next_at_ms": number;
    "next_id": string;
}

export interface Plan {
    "note_id": string;
    "snapshot_id": string;
    "title": string;
    "author_id": string;
    "author_name": string;
    "account_id": string;
    "config": Config;
    "relative_directory": string;
    "items": PlannedItem[] | null;
    "warnings": string[] | null;
    "hash": string;
}

export interface PlanInput {
    "snapshot_id": string;
    "config": Config;
}

export interface PlannedItem {
    "sequence": number;
    "kind": MediaKind;
    "asset_key": string;
    "confidence": IdentityConfidence;
    "representation": Representation;
    "relative_path": string;
    "urls": string[] | null;
    "expected_bytes": number | null;
}

export interface Representation {
    "codec_group"?: string;
    "codec"?: string;
    "format"?: string;
    "scene"?: string;
    "width"?: number | null;
    "height"?: number | null;
    "fps"?: number | null;
    "image_index"?: number | null;
}

export interface Result {
    "root": string;
    "relative_path": string;
    "bytes": number;
    "sha256": string;
    "mtime_ms": number;
    "skip_reason": SkipReason;
    "reused_item_id": string;
}

export enum SkipReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    SkipNone = 0,
    SkipHistory = 1,
    SkipFileExists = 2,
};

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Unknown = 0,
    Queued = 1,
    Resolving = 2,
    Running = 3,
    Paused = 4,
    WaitingRetry = 5,
    Succeeded = 6,
    Partial = 7,
    Failed = 8,
    Canceled = 9,
    Interrupted = 10,
};

export interface Task {
    "id": string;
    "note_id": string;
    "snapshot_id": string;
    "title": string;
    "author_id": string;
    "author_name": string;
    "account_id": string;
    "state": State;
    "config": Config;
    "relative_directory": string;
    "plan_hash": string;
    "planned_items": number;
    "successful_items": number;
    "skipped_items": number;
    "failed_items": number;
    "fulfilled_items": number;
    "completed_bytes": number;
    "transferred_bytes": number;
    "current_item_id": string;
    "current_sequence": number;
    "current_bytes": number;
    "current_total": number | null;
    "failure": Failure | null;
    "created_at_ms": number;
    "started_at_ms": number | null;
    "finished_at_ms": number | null;
    "updated_at_ms": number;
    "revision": number;
}
