// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum Profile {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ProfileUnknown = 0,
    Development = 1,
    Production = 2,
};
