// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../modules/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as paths$0 from "../../platform/paths/models.js";

export interface Bootstrap {
    "name": string;
    "version": string;
    "profile": paths$0.Profile;
    "state": RuntimeState;
    "data_directory": string;
    "default_download_directory": string;
    "schema_version": number;
    "settings": settings$0.General;
}

export enum RuntimeState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StateUnknown = 0,
    StateStarting = 1,
    StateReady = 2,
    StateClosing = 3,
    StateClosed = 4,
    StateFailed = 5,
};
