// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accounts$0 from "../modules/accounts/models.js";

export function Create(input: accounts$0.Create): $CancellablePromise<accounts$0.Account> {
    return $Call.ByID(632065335, input);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(349480652, id);
}

export function List(): $CancellablePromise<accounts$0.Account[] | null> {
    return $Call.ByID(524276439);
}

export function ReplaceCookie(input: accounts$0.ReplaceCookie): $CancellablePromise<accounts$0.Account> {
    return $Call.ByID(4194008379, input);
}

export function SetDefault(id: string): $CancellablePromise<accounts$0.Account> {
    return $Call.ByID(980203758, id);
}

export function Update(input: accounts$0.Update): $CancellablePromise<accounts$0.Account> {
    return $Call.ByID(644556318, input);
}

export function Validate(id: string): $CancellablePromise<accounts$0.Account> {
    return $Call.ByID(4149256081, id);
}
