// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as downloads$0 from "../modules/downloads/models.js";

export function BuildPlan(i: downloads$0.PlanInput): $CancellablePromise<downloads$0.Plan> {
    return $Call.ByID(849018733, i);
}

export function BuildPlans(i: downloads$0.BatchPlanInput): $CancellablePromise<downloads$0.Plan[] | null> {
    return $Call.ByID(3355417658, i);
}

export function Cancel(id: string): $CancellablePromise<downloads$0.Task> {
    return $Call.ByID(4108082228, id);
}

export function CreateTask(i: downloads$0.CreateTask): $CancellablePromise<downloads$0.Task> {
    return $Call.ByID(2516981815, i);
}

export function CreateTasks(i: downloads$0.CreateBatch): $CancellablePromise<downloads$0.Batch> {
    return $Call.ByID(1872245516, i);
}

export function DeletePreset(id: string): $CancellablePromise<void> {
    return $Call.ByID(2557475658, id);
}

export function GetActiveSnapshots(): $CancellablePromise<downloads$0.ActiveSnapshot> {
    return $Call.ByID(1079394449);
}

export function GetCandidates(id: string): $CancellablePromise<downloads$0.CandidateCatalog> {
    return $Call.ByID(2117973064, id);
}

export function GetChangesSince(i: downloads$0.ChangesInput): $CancellablePromise<downloads$0.Changes> {
    return $Call.ByID(3342264927, i);
}

export function GetDefaultConfig(): $CancellablePromise<downloads$0.Config> {
    return $Call.ByID(586874101);
}

export function GetTask(id: string): $CancellablePromise<downloads$0.Task> {
    return $Call.ByID(1800166727, id);
}

export function ListPresets(): $CancellablePromise<downloads$0.Preset[] | null> {
    return $Call.ByID(4259642326);
}

export function ListTaskItems(id: string): $CancellablePromise<downloads$0.Item[] | null> {
    return $Call.ByID(783159849, id);
}

export function ListTasks(i: downloads$0.ListInput): $CancellablePromise<downloads$0.Page> {
    return $Call.ByID(1821662076, i);
}

export function OpenDirectory(id: string): $CancellablePromise<void> {
    return $Call.ByID(3856535493, id);
}

export function Pause(id: string): $CancellablePromise<downloads$0.Task> {
    return $Call.ByID(838565016, id);
}

export function PreviewPlans(i: downloads$0.BatchPlanInput): $CancellablePromise<downloads$0.PlanPreview[] | null> {
    return $Call.ByID(3535149310, i);
}

export function QueryHistory(i: downloads$0.ListInput): $CancellablePromise<downloads$0.Page> {
    return $Call.ByID(1209233090, i);
}

export function Resume(id: string): $CancellablePromise<downloads$0.Task> {
    return $Call.ByID(1893955865, id);
}

export function RetryFailed(id: string): $CancellablePromise<downloads$0.Task> {
    return $Call.ByID(3842148121, id);
}

export function SavePreset(i: downloads$0.SavePreset): $CancellablePromise<downloads$0.Preset> {
    return $Call.ByID(570049148, i);
}
