// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notes$0 from "../modules/notes/models.js";

export function CancelParse(id: string): $CancellablePromise<notes$0.ParseJob> {
    return $Call.ByID(1524271575, id);
}

export function GetNote(id: string): $CancellablePromise<notes$0.Detail> {
    return $Call.ByID(3519035170, id);
}

export function GetParseJob(id: string): $CancellablePromise<notes$0.ParseJob> {
    return $Call.ByID(577789616, id);
}

export function GetRawSnapshot(id: string): $CancellablePromise<string> {
    return $Call.ByID(3769768292, id);
}

export function GetSnapshot(id: string): $CancellablePromise<notes$0.Detail> {
    return $Call.ByID(1832383546, id);
}

export function ListNotes(input: notes$0.ListInput): $CancellablePromise<notes$0.Page> {
    return $Call.ByID(640852195, input);
}

export function ListParseJobs(): $CancellablePromise<notes$0.ParseJob[] | null> {
    return $Call.ByID(2120083481);
}

export function ListSnapshots(id: string): $CancellablePromise<notes$0.Snapshot[] | null> {
    return $Call.ByID(93412171, id);
}

export function StartParse(input: notes$0.StartParse): $CancellablePromise<notes$0.ParseJob> {
    return $Call.ByID(3173646677, input);
}
