// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as parsing$0 from "../modules/parsing/models.js";

export function Cancel(id: string): $CancellablePromise<parsing$0.Job> {
    return $Call.ByID(972034202, id);
}

export function Get(id: string): $CancellablePromise<parsing$0.Job> {
    return $Call.ByID(2833979420, id);
}

export function GetDefaultConfig(): $CancellablePromise<parsing$0.Config> {
    return $Call.ByID(1519870163);
}

export function Items(q: parsing$0.ItemQuery): $CancellablePromise<parsing$0.ItemPage> {
    return $Call.ByID(3612017876, q);
}

export function List(): $CancellablePromise<parsing$0.Job[] | null> {
    return $Call.ByID(564214536);
}

export function Origins(id: string): $CancellablePromise<parsing$0.Origin[] | null> {
    return $Call.ByID(1917497699, id);
}

export function Pause(id: string): $CancellablePromise<parsing$0.Job> {
    return $Call.ByID(432304658, id);
}

export function Resume(id: string): $CancellablePromise<parsing$0.Job> {
    return $Call.ByID(3662446067, id);
}

export function RetryFailed(id: string): $CancellablePromise<parsing$0.Job> {
    return $Call.ByID(3114031123, id);
}

export function Sources(id: string): $CancellablePromise<parsing$0.Source[] | null> {
    return $Call.ByID(872499650, id);
}

export function Start(i: parsing$0.Start): $CancellablePromise<parsing$0.Job> {
    return $Call.ByID(2033217084, i);
}
