// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../modules/settings/models.js";

export function GetGeneral(): $CancellablePromise<settings$0.General> {
    return $Call.ByID(4087961979);
}

export function UpdateGeneral(input: settings$0.UpdateGeneral): $CancellablePromise<settings$0.General> {
    return $Call.ByID(494463698, input);
}
