// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account is safe to send to the UI; it never contains a Cookie or ciphertext.
 */
export interface Account {
    "id": string;
    "name": string;
    "user_id": string;
    "nickname": string;
    "status": Status;
    "enabled": boolean;
    "is_default": boolean;
    "has_cookie": boolean;
    "credential_version": number;
    "validated_at_ms": number | null;
    "last_error": string;
    "created_at_ms": number;
    "updated_at_ms": number;
}

export interface Create {
    "name": string;
    "cookie": string;
}

export interface ReplaceCookie {
    "id": string;
    "cookie": string;
    "expected_version": number;
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Unknown = 0,
    Unchecked = 1,
    Valid = 2,
    Expired = 3,
    Restricted = 4,
    Disabled = 5,
    Error = 6,
};

export interface Update {
    "id": string;
    "name": string;
    "enabled": boolean;
}
