// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notes$0 from "../notes/models.js";

export enum AccountMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    AccountUnknown = 0,
    AccountFixed = 1,
    AccountBySource = 2,
};

export enum CacheMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CacheUnknown = 0,
    UseFresh = 1,
    ForceRefresh = 2,
    CacheOnly = 3,
};

export interface Config {
    "max_pages": number;
    "max_notes": number;
    "concurrency": number;
    "account_mode": AccountMode;
    "account_ids": string[] | null;
    "cache_mode": CacheMode;
    "cache_ttl_ms": number;
    "kind": notes$0.Kind;
    "published_from_ms": number;
    "published_until_ms": number;
    "title_keyword": string;
    "live_photo": LiveFilter;
    "save_raw": boolean;
}

export interface Item {
    "id": string;
    "job_id": string;
    "note_id": string;
    "title": string;
    "raw_kind": string;
    "account_id": string;
    "credential_version": number;
    "state": ItemState;
    "snapshot_id": string;
    "failure": notes$0.Failure | null;
    "skip_reason": string;
    "origin_count": number;
    "ordinal": number;
    "published_at_ms": number | null;
}

export interface ItemPage {
    "items": Item[] | null;
    "has_more": boolean;
    "next_ordinal": number;
}

export interface ItemQuery {
    "job_id": string;
    "limit": number;
    "after_ordinal": number;
    "state": ItemState;
}

export enum ItemState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ItemUnknown = 0,
    Pending = 1,
    Resolving = 2,
    Complete = 3,
    ItemFailed = 4,
    Skipped = 5,
    Incomplete = 6,
    ItemInterrupted = 7,
    ItemCanceled = 8,
};

export interface Job {
    "id": string;
    "mode": Mode;
    "state": State;
    "config": Config;
    "source_count": number;
    "discovered": number;
    "completed": number;
    "failed_items": number;
    "skipped_items": number;
    "active_items": number;
    "failure": notes$0.Failure | null;
    "limit_reason": string;
    "created_at_ms": number;
    "updated_at_ms": number;
    "revision": number;
    "run_version": number;
}

export enum LiveFilter {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    LiveAny = 0,
    LiveOnly = 1,
    LiveExclude = 2,
};

export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ModeUnknown = 0,
    ModeNotes = 1,
    ModeUsers = 2,
};

export interface Origin {
    "index": number;
    "target_id": string;
    "account_id": string;
    "pages": number;
}

export interface Source {
    "id": string;
    "job_id": string;
    "index": number;
    "target_id": string;
    "account_id": string;
    "credential_version": number;
    "state": SourceState;
    "pages": number;
    "has_more": boolean;
    "user_name": string;
    "failure": notes$0.Failure | null;
    "limit_reason": string;
}

export enum SourceState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    SourceUnknown = 0,
    SourcePending = 1,
    SourceRunning = 2,
    SourceComplete = 3,
    SourceFailed = 4,
    SourceLimited = 5,
};

export interface Start {
    "request_id": string;
    "mode": Mode;
    "account_id": string;
    "text": string;
    "config": Config;
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StateUnknown = 0,
    Queued = 1,
    Running = 2,
    Succeeded = 3,
    Partial = 4,
    Failed = 5,
    Paused = 6,
    Canceled = 7,
    Interrupted = 8,
    Limited = 9,
};
