// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * General contains application settings, not a running task's config snapshot.
 */
export interface General {
    "schema_version": number;
    "theme_mode": ThemeMode;
    "max_concurrent_notes": number;
    "output_directory": string;
    "revision": number;
    "updated_at_ms": number;
}

export enum ThemeMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ThemeUnknown = 0,
    ThemeSystem = 1,
    ThemeLight = 2,
    ThemeDark = 3,
};

export interface UpdateGeneral {
    "theme_mode": ThemeMode;
    "max_concurrent_notes": number;
    "output_directory": string;
    "expected_revision": number;
}
