// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as xhsapi$0 from "../../xhsapi/models.js";

export interface Detail {
    "snapshot": Snapshot;
    "note": xhsapi$0.Note;
}

export enum ErrorKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ErrorUnknown = 0,
    ErrorAccount = 1,
    ErrorUnauthorized = 2,
    ErrorRestricted = 3,
    ErrorRateLimited = 4,
    ErrorNetwork = 5,
    ErrorResponse = 6,
    ErrorStorage = 7,
    ErrorCanceled = 8,
};

export interface Failure {
    "kind": ErrorKind;
    "message": string;
    "http_status": number;
    "upstream_code": number;
    "retryable": boolean;
}

export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    KindUnknown = 0,
    KindImage = 1,
    KindVideo = 2,
};

export interface ListInput {
    "limit": number;
    "before_at_ms": number;
    "before_id": string;
}

export interface Page {
    "items": Summary[] | null;
    "has_more": boolean;
    "next_at_ms": number;
    "next_id": string;
}

export interface ParseJob {
    "id": string;
    "request_id": string;
    "account_id": string;
    "note_id": string;
    "snapshot_id": string;
    "state": ParseState;
    "failure": Failure | null;
    "created_at_ms": number;
    "started_at_ms": number | null;
    "finished_at_ms": number | null;
    "updated_at_ms": number;
    "revision": number;
}

export enum ParseState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ParseUnknown = 0,
    ParseQueued = 1,
    ParseRunning = 2,
    ParseCompleted = 3,
    ParseFailed = 4,
    ParseCanceled = 5,
    ParseInterrupted = 6,
};

export interface Snapshot {
    "id": string;
    "note_id": string;
    "account_id": string;
    "credential_version": number;
    "parser_version": number;
    "warnings": string[] | null;
    "fetched_at_ms": number;
    "raw_sha256": string;
    "raw_available": boolean;
}

export interface StartParse {
    "request_id": string;
    "account_id": string;
    "input": string;
}

export interface Summary {
    "id": string;
    "author_id": string;
    "author_name": string;
    "kind": Kind;
    "raw_kind": string;
    "title": string;
    "description": string;
    "has_live_photo": boolean;
    "image_count": number;
    "video_stream_count": number;
    "motion_stream_count": number;
    "cover_url": string;
    "published_at_ms": number | null;
    "modified_at_ms": number | null;
    "fetched_at_ms": number;
    "snapshot_id": string;
}
