import {
  AccountStatus,
  AccountMode,
  CacheMode,
  CollectionMode,
  CollectionState,
  CollectionItemState,
  DedupMode,
  ExistingPolicy,
  ImageMode,
  LiveFilter,
  LiveMode,
  MediaKind,
  Profile,
  ThemeMode,
  type Account,
  type Bootstrap,
  type CandidateCatalog,
  type CollectionConfig,
  type CollectionItem,
  type CollectionJob,
  type DownloadConfig,
  type NoteDetail,
  type PlanPreview,
} from '@/shared/contracts';
import { RuntimeState } from '../../bindings/github.com/cry5tallize/xhs_spider_desktop/internal/bridge/dto/models';
import { automaticVideo } from '@/features/downloads/selection';

export const fixtureNoteID = 'aaaaaaaaaaaaaaaaaaaaaaaa';
export const fixtureUserID = 'bbbbbbbbbbbbbbbbbbbbbbbb';
export const fixtureAccount: Account = {
  id: 'account',
  name: '账号备注',
  nickname: '登录用户',
  user_id: fixtureUserID,
  avatar_url: 'https://cdn.example.test/account.png',
  status: AccountStatus.Valid,
  enabled: true,
  is_default: true,
  has_cookie: true,
  credential_version: 1,
  validated_at_ms: 1,
  last_error: '',
  created_at_ms: 1,
  updated_at_ms: 1,
};
export const fixtureBootstrap: Bootstrap = {
  name: 'XHS Desktop',
  version: '0.1.0',
  profile: Profile.Development,
  state: RuntimeState.StateReady,
  data_directory: 'D:\\data',
  default_download_directory: 'D:\\Downloads',
  schema_version: 7,
  settings: {
    schema_version: 1,
    theme_mode: ThemeMode.ThemeLight,
    max_concurrent_notes: 4,
    output_directory: '',
    revision: 1,
    updated_at_ms: 1,
  },
};
export const fixtureCollectionConfig: CollectionConfig = {
  max_pages: 100,
  max_notes: 0,
  concurrency: 2,
  account_mode: AccountMode.AccountFixed,
  account_ids: [],
  cache_mode: CacheMode.UseFresh,
  cache_ttl_ms: 600000,
  kind: 0,
  published_from_ms: 0,
  published_until_ms: 0,
  title_keyword: '',
  live_photo: LiveFilter.LiveAny,
  save_raw: true,
};
export const fixtureJob: CollectionJob = {
  id: 'job',
  mode: CollectionMode.ModeNotes,
  state: CollectionState.Succeeded,
  config: fixtureCollectionConfig,
  source_count: 1,
  discovered: 1,
  completed: 1,
  failed_items: 0,
  skipped_items: 0,
  active_items: 0,
  failure: null,
  limit_reason: '',
  created_at_ms: 1,
  updated_at_ms: 1,
  revision: 2,
  run_version: 1,
};
export const fixtureItem: CollectionItem = {
  id: 'item',
  job_id: 'job',
  note_id: fixtureNoteID,
  title: '解析结果',
  raw_kind: 'video',
  account_id: 'account',
  credential_version: 1,
  state: CollectionItemState.Complete,
  snapshot_id: 'snapshot',
  failure: null,
  skip_reason: '',
  origin_count: 1,
  ordinal: 1,
  published_at_ms: 1,
  author_id: fixtureUserID,
  author_name: '测试作者',
  author_avatar: 'https://cdn.example.test/author.png',
  cover_url: 'https://cdn.example.test/photo.png',
  image_count: 1,
  video_stream_count: 1,
  has_live_photo: true,
  live_photo_count: 1,
};
export function fixtureDownloadConfig(): DownloadConfig {
  return {
    schema_version: 1,
    media: {
      video: true,
      images: true,
      live_photo_motion: true,
      video_cover: false,
      pretty: true,
      text: false,
      raw: false,
      manifest: true,
    },
    output: { directory: 'D:\\Downloads', existing_policy: ExistingPolicy.Overwrite },
    dedup: { mode: DedupMode.SameOutput, force: false, strict_hash: false },
    execution: { continue_on_error: true, retries_per_url: 2, max_attempts: 12 },
    selection: {
      video: automaticVideo(),
      images: {
        mode: ImageMode.ImageBest,
        candidate_ids: [],
        scenes: [],
        formats: [],
        first_index: 0,
        last_index: 0,
      },
      live_photo: LiveMode.LiveBoth,
    },
    naming: { directory_template: '', file_template: '' },
  };
}
export const fixtureCatalog: CandidateCatalog = {
  snapshot_id: 'snapshot',
  note_type: 'video',
  codec_groups: ['EF1'],
  scenes: ['WebDft'],
  formats: ['mp4', 'jpg'],
  candidates: [
    {
      id: 'main',
      kind: MediaKind.MediaVideo,
      representation: {
        codec: 'h264',
        codec_group: 'EF1',
        width: 1080,
        height: 1920,
        format: 'mp4',
      },
      urls: ['https://cdn.example.test/video.mp4'],
      expected_bytes: 1024,
      live_photo: false,
      scenes: [],
    },
    {
      id: 'image',
      kind: MediaKind.MediaImage,
      representation: { format: 'jpg', image_index: 1 },
      urls: ['https://cdn.example.test/photo.jpg'],
      expected_bytes: 256,
      live_photo: true,
      scenes: ['WebDft'],
    },
    {
      id: 'motion',
      kind: MediaKind.MediaMotion,
      representation: { codec: 'h265', codec_group: 'EF4', format: 'mp4', image_index: 1 },
      urls: ['https://cdn.example.test/motion.mp4'],
      expected_bytes: 512,
      live_photo: true,
      scenes: [],
    },
  ],
};
export function fixturePreview(kind = MediaKind.MediaVideo): PlanPreview {
  return {
    snapshot_id: 'snapshot',
    note_id: fixtureNoteID,
    title: '解析结果',
    directory: 'author/note',
    files: [
      {
        sequence: 1,
        kind,
        representation: { width: 1080, height: 1920 },
        bytes: 1024,
        relative_path: 'author/note/video.mp4',
      },
    ],
    known_bytes: 1024,
    unknown_sizes: 0,
    warnings: [],
  };
}
export const fixtureDetail: NoteDetail = {
  snapshot: {
    id: 'snapshot',
    note_id: fixtureNoteID,
    account_id: 'account',
    credential_version: 1,
    parser_version: 1,
    warnings: [],
    fetched_at_ms: 1,
    raw_sha256: '',
    raw_available: true,
  },
  note: {
    id: fixtureNoteID,
    type: 'normal',
    title: '解析结果',
    description: '笔记正文',
    user: {
      id: fixtureUserID,
      nickname: '测试作者',
      avatar_url: 'https://cdn.example.test/author.png',
    },
    interactions: {},
    tags: [],
    mentioned_users: [],
    has_live_photo: true,
    images: [
      {
        index: 0,
        variants: [
          {
            scene: 'WebDft',
            source: 'info_list',
            index: 0,
            url: 'https://cdn.example.test/photo.png',
            sources: [],
          },
        ],
        motion_streams: [],
        stream_groups: [],
      },
    ],
  },
};
