// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

export interface ImageVariant {
    "scene"?: string;
    "source": string;
    "index": number;
    "url": string;
    "format"?: string;
    "width"?: number | null;
    "height"?: number | null;
    "sources": ImageVariantSource[] | null;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

/**
 * All entries share their parent variant's URL. Sources keep alternate scenes
 * and metadata without repeating that URL in the normalized output.
 */
export interface ImageVariantSource {
    "scene"?: string;
    "source": string;
    "index": number;
    "format"?: string;
    "width"?: number | null;
    "height"?: number | null;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

/**
 * Note is a normalized feed item. Type retains the server's open-ended value;
 * a normal note may contain both ordinary images and LivePhotos.
 */
export interface Note {
    "id": string;
    "item_id"?: string;
    "type": string;
    "model_type"?: string;
    "title": string;
    "description": string;
    "user": NoteUser;
    "interactions": NoteInteractions;
    "tags": NoteTag[] | null;
    "mentioned_users": NoteUser[] | null;
    "created_at_ms"?: number | null;
    "updated_at_ms"?: number | null;
    "ip_location"?: string;
    "share_info"?: json$0.RawMessage;
    "images": NoteImageInfo[] | null;
    "video"?: NoteVideoInfo | null;
    "has_live_photo": boolean;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
    "item_extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

export interface NoteImageInfo {
    "index": number;
    "file_id"?: string;
    "trace_id"?: string;
    "width"?: number | null;
    "height"?: number | null;
    "live_photo"?: boolean | null;
    "variants": ImageVariant[] | null;
    "motion_streams": VideoStream[] | null;
    "stream_groups": string[] | null;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

export interface NoteInteractions {
    "likes"?: number | null;
    "collections"?: number | null;
    "comments"?: number | null;
    "shares"?: number | null;
    "nice_count"?: number | null;
    "liked"?: boolean | null;
    "collected"?: boolean | null;
    "followed"?: boolean | null;
    "relation"?: string;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

export interface NoteTag {
    "id": string;
    "name": string;
    "type": string;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

export interface NoteUser {
    "id": string;
    "nickname": string;
    "avatar_url"?: string;
    "xsec_token"?: string;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

export interface NoteVideoInfo {
    "video_id"?: string;
    "metadata": VideoMetadata;
    "capa_duration_sec"?: number | null;
    "image": VideoImageInfo;
    "streams": VideoStream[] | null;
    "sources": VideoMediaSource[] | null;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

export interface VideoImageInfo {
    "first_frame_file_id"?: string;
    "thumbnail_file_id"?: string;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

/**
 * VideoMediaSource keeps metadata and all original groups, including empty ones.
 */
export interface VideoMediaSource {
    "name": string;
    "video_id"?: string;
    "metadata": VideoMetadata;
    "stream_groups": string[] | null;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

/**
 * VideoMetadata is distinct from StreamMetadata: its duration is in seconds.
 */
export interface VideoMetadata {
    "biz_id"?: string;
    "biz_name"?: number | null;
    "duration_sec"?: number | null;
    "width"?: number | null;
    "height"?: number | null;
    "md5"?: string;
    "hdr_type"?: number | null;
    "drm_type"?: number | null;
    "stream_types"?: number[] | null;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

export interface VideoStream {
    "stream_type"?: number | null;
    "stream_desc"?: string;
    "default_stream"?: number | null;
    "format"?: string;
    "quality_type"?: string;
    "width"?: number | null;
    "height"?: number | null;
    "fps"?: number | null;
    "size_bytes"?: number | null;
    "duration_ms"?: number | null;
    "video_duration_ms"?: number | null;
    "audio_duration_ms"?: number | null;
    "average_bitrate"?: number | null;
    "video_bitrate"?: number | null;
    "audio_bitrate"?: number | null;
    "video_codec"?: string;
    "audio_codec"?: string;
    "audio_channels"?: number | null;
    "rotate"?: number | null;
    "volume"?: number | null;
    "hdr_type"?: number | null;
    "weight"?: number | null;
    "vmaf"?: number | null;
    "psnr"?: number | null;
    "ssim"?: number | null;
    "sr"?: number | null;
    "codec_group": string;
    "codec": string;
    "master_url"?: string;
    "url"?: string;
    "backup_urls": string[] | null;
    "sources": VideoStreamSource[] | null;
    "extra"?: { [_ in string]?: json$0.RawMessage } | null;
}

/**
 * Raw includes original values in memory. It is omitted from Pretty JSON to
 * avoid repeating links; the complete input is saved separately by the cmd.
 */
export interface VideoStreamSource {
    "name": string;
    "codec_group": string;
    "group_index": number;
    "index": number;
}
